language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: rSN+BbykHh6Wjfd34qdvfdsI9zdeVCNFeK+4AHYVmTa/gKfz6ocia+Y5oOoF+P+nHkGLOnilaZ5qpjcjedF+tLQ9K8ChVHsL3E3MGXVcSBp5puhqO5a7rRYkGBbvjSF1s3msd6Vo0kQX1WY5n/Ou8HFB/764aC+ciM/wxJkjqdc0lfVxygSpzgKOOmKSd9jMrhqhEreUYMkr+VIKG1BmG5go0mNy+fQlw6LTBIM/er/CxlJK72EhuBcq51QBcZisFSm7XMfnPX1un64i6Bp1+zqq+NVH8TcWpyHpVL5chyJcKp/4SShQw/mRH+O70HxkhCxtXmg2601y4ZhmgiCIrbv5JBx3tiDvsMYG7opUCf3hpB1IOnMyMs7zLyJiLxncLjdbCvVPT341T5KPPA5etuxXFAFYs+5bezWgvz19CHvmWFo7vgaN0jENY56/Sy/DFGtXInhm0aLVxyHtUKklN1ZWQqF1XkzVzFSaXc/fMKNTvoQJ2wdLHzqRPXwj5xyaaWoXwx8osijNO5Yziy9aem0C4LQ+gfAJZemrQkDyX/ngv6Y2rVlDYI9hZQWYnCI/2xjRjGGmcEmXiolE3tsvvY93kQFNv/OJ3cFMo+fttsbInQp3gkzbc9etaiO+oNghpz0sP/7GrVukzvcUKpG22a/zSSL3TzuvnvCgVQjoSSg=
  app: obscure-woodland-76305
  on:
    repo: bosoxfan3/Woofle
